### ISSUE TITLE
Build fails in getAppInstanceId()

### ISSUE THREAD

**Issue by grigorig** [capacitor-community/firebase-analytics#97]
**Describe the bug**
The plugin native build fails in the function `getAppInstanceId()` with the error `Cannot force unwrap value of non-optional type 'String'`. 

This seems to be a version conflict of the native Firebase SDKs. The return type of the native Firebase SDK function `Analytics.appInstanceId()` was changed at some point and Cocoapods decided to install the wrong version for this plugin. I also use the Capacitor Firebase Crashlytics plugin, maybe that's why.

Maybe this plugin should define the required Firebase SDK version range in `Podfile`?

**To Reproduce**
1. Install both this plugin and `@capacitor-community/firebase-crashlytics`
2. Run Capacitor update/sync
2. Build project

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - CocoaPods: 1.10.1
 - Version: 1.0.0

**Comment by brownoxford** [comment]
Can you please try `@capacitor-community/firebase-analytics@1.0.1-alpha.0`? I've locked the pod dependency to the latest v8 of upstream Firebase/Analytics.

If you get this error compiling, you may need to run `pod repo update` to ensure your source repos are up to date:

```CocoaPods could not find compatible versions for pod "Firebase/Analytics"```

**Comment by jorisbertomeu** [comment]
Hey, I have same issue with my app. I tried to add `@capacitor-community/firebase-analytics@1.0.1-alpha.0` but it does not work.
I can notice some abnormal verbose `@capacitor-community/firebase-crashlytics: No matching version found for @capacitor-community/firebase-crashlytics@v1.0.1-alpha.0.`.

Here is full trace from NPM debug file for `npm install @capacitor-community/firebase-analytics@v1.0.1-alpha.0 --save` :

```
25 timing npm:load Completed in 14ms
26 timing config:load:flatten Completed in 3ms
27 timing arborist:ctor Completed in 1ms
28 timing arborist:ctor Completed in 0ms
29 timing idealTree:init Completed in 2661ms
30 timing idealTree:userRequests Completed in 10ms
31 silly idealTree buildDeps
32 silly fetch manifest @capacitor-community/firebase-crashlytics@v1.0.1-alpha.0
33 http fetch GET 304 https://registry.npmjs.org/@capacitor-community%2ffirebase-crashlytics 319ms (from cache)
34 silly placeDep ROOT @capacitor-community/firebase-crashlytics@ REPLACE for: edlv2-app@0.0.1 want: v1.0.1-alpha.0
35 timing idealTree:#root Completed in 330ms
36 timing idealTree:node_modules/@capacitor-community/firebase-crashlytics Completed in 0ms
37 timing idealTree:buildDeps Completed in 331ms
38 timing idealTree:fixDepFlags Completed in 10ms
39 timing idealTree Completed in 3014ms
40 timing command:install Completed in 3024ms
41 verbose type version
42 verbose stack @capacitor-community/firebase-crashlytics: No matching version found for @capacitor-community/firebase-crashlytics@v1.0.1-alpha.0.
42 verbose stack     at module.exports (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
42 verbose stack     at /Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
42 verbose stack     at async Arborist.[nodeFromEdge] (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:947:19)
42 verbose stack     at async Arborist.[buildDepStep] (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:893:11)
42 verbose stack     at async Arborist.buildIdealTree (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:7)
42 verbose stack     at async Promise.all (index 1)
42 verbose stack     at async Arborist.reify (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:135:5)
42 verbose stack     at async Install.install (/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/lib/node_modules/npm/lib/install.js:137:5)
43 verbose cwd /Users/jorisbertomeu/Work/edlv2-app
44 verbose Darwin 21.0.0
45 verbose argv "/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/bin/node" "/Users/jorisbertomeu/.nvm/versions/node/v14.11.0/bin/npm" "install" "@capacitor-community/firebase-crashlytics@v1.0.1-alpha.0" "--save"
46 verbose node v14.11.0
47 verbose npm  v7.12.0
48 error code ETARGET
49 error notarget No matching version found for @capacitor-community/firebase-crashlytics@v1.0.1-alpha.0.
50 error notarget In most cases you or one of your dependencies are requesting
50 error notarget a package version that doesn't exist.
51 verbose exit 1
```

My NPM dependencies here:


```
"@angular/animations": "^10.1.2",
"@angular/common": "~10.0.0",
"@angular/core": "~10.0.0",
"@angular/forms": "~10.0.0",
"@angular/platform-browser": "~10.0.0",
"@angular/platform-browser-dynamic": "~10.0.0",
"@angular/router": "~10.0.0",
"@asymmetrik/ngx-leaflet": "^8.1.0",
"@capacitor-community/firebase-analytics": "^1.0.0",
"@capacitor-community/firebase-crashlytics": "1.0.1-alpha.0",
"@capacitor/android": "^3.0.1",
"@capacitor/camera": "^1.0.1",
"@capacitor/core": "3.0.1",
"@capacitor/ios": "^3.0.1",
"@capacitor/push-notifications": "^1.0.1",
"@capacitor/splash-screen": "^1.0.1",
"@ionic-native/android-full-screen": "^5.28.0",
"@ionic-native/android-permissions": "^5.29.0",
"@ionic-native/app-preferences": "^5.28.0",
"@ionic-native/app-version": "^5.28.0",
"@ionic-native/badge": "^5.31.1",
"@ionic-native/calendar": "^5.28.0",
"@ionic-native/call-number": "^5.28.0",
"@ionic-native/camera": "^5.28.0",
"@ionic-native/camera-preview": "^5.28.0",
"@ionic-native/clipboard": "^5.28.0",
"@ionic-native/cloud-settings": "^5.29.0",
"@ionic-native/core": "^5.0.0",
"@ionic-native/device": "^5.29.0",
"@ionic-native/diagnostic": "^5.28.0",
"@ionic-native/document-scanner": "^5.30.0",
"@ionic-native/document-viewer": "^5.28.0",
"@ionic-native/extended-device-information": "^5.29.0",
"@ionic-native/fcm": "^5.28.0",
"@ionic-native/file": "^5.28.0",
"@ionic-native/file-opener": "^5.28.0",
"@ionic-native/file-transfer": "^5.28.0",
"@ionic-native/flashlight": "^5.28.0",
"@ionic-native/geolocation": "^5.28.0",
"@ionic-native/http": "^5.28.0",
"@ionic-native/in-app-browser": "^5.28.0",
"@ionic-native/in-app-purchase-2": "^5.29.0",
"@ionic-native/in-app-review": "^5.28.0",
"@ionic-native/insomnia": "^5.28.0",
"@ionic-native/keyboard": "^5.28.0",
"@ionic-native/launch-navigator": "^5.28.0",
"@ionic-native/media-capture": "^5.28.0",
"@ionic-native/native-geocoder": "^5.28.0",
"@ionic-native/network": "^5.28.0",
"@ionic-native/photo-viewer": "^5.28.0",
"@ionic-native/screen-orientation": "^5.28.0",
"@ionic-native/sms": "^5.28.0",
"@ionic-native/social-sharing": "^5.28.0",
"@ionic-native/splash-screen": "^5.0.0",
"@ionic-native/status-bar": "^5.0.0",
"@ionic-native/streaming-media": "^5.28.0",
"@ionic-native/vibration": "^5.28.0",
"@ionic/angular": "^5.5.3",
"@ionic/storage": "^2.3.1",
"@kolkov/angular-editor": "^1.1.4",
"angular-ng-autocomplete": "^2.0.1",
"chart.js": "^2.9.3",
"cordova-plugin-actionsheet": "^2.3.3",
"cordova-plugin-dialogs": "^2.0.2",
"cordova-plugin-file": "^6.0.2",
"deep-diff": "^1.0.2",
"es6-promise-plugin": "^4.2.2",
"google-libphonenumber": "^3.2.13",
"ionic4-auto-complete": "^2.9.4",
"leaflet": "^1.7.1",
"moment": "^2.29.0",
"ng-simple-slideshow": "^1.3.0-beta.11",
"ng2-pdf-viewer": "^6.3.2",
"ngx-filter-pipe": "^2.1.2",
"ngx-moment": "^5.0.0",
"ngx-order-pipe": "^2.1.0",
"ngx-pinch-zoom": "^2.4.4",
"rxjs": "~6.5.5",
"ts-md5": "^1.2.7",
"ts-serializer": "^2.2.6",
"tslib": "^2.0.0",
"zone.js": "~0.10.3"
```

Maybe it can help you for debug ? Anyway, thanks for your work ;)

**Comment by brownoxford** [comment]
Hi @jorisbertomeu, try using v1.0.1-alpha.0 of the the firebase-analytics plugin (not firebase-crashlytics).

**Comment by jorisbertomeu** [comment]
Hey @brownoxford, thanks for your quick reply 🙂
This is a mistake from myself when I copy/past .. The log output I provided is generated when I install firebase-analytics.
Here is real output from my terminal:
```
> npm install @capacitor-community/firebase-analytics@v1.0.1-alpha.0 --save
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @capacitor-community/firebase-crashlytics@1.0.1-alpha.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jorisbertomeu/.npm/_logs/2021-06-14T19_39_13_466Z-debug.log
```

NB: It is as if there was a conflict with firebase-crashlytics .. ? 🧐

**Comment by brownoxford** [comment]
It still looks like you are trying to install `@capacitor-community/firebase-crashlytics@1.0.1-alpha.0`

**Comment by grigorig** [comment]
I can confirm it's looking good here now. Turned out I misunderstood a little bit how CocoaPods' dependency management actually works, too.

**Comment by brownoxford** [comment]
Thanks @grigorig I'll close this out
